# Generated by Django 6.0.6 on 2026-06-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('liftback', 'Liftback'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('grand_coupe', 'Grand Coupe'), ('crossover', 'Crossover')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carbody_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.carbody')),
                ('car_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Name')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Color')),
                ('horsepower', models.IntegerField(blank=True, null=True, verbose_name='Horse Power')),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine Number')),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine Type')),
                ('engine_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine Size')),
                ('manufactured_year', models.IntegerField(blank=True, null=True, verbose_name='Manufactured Year')),
            ],
            bases=('data.carbody',),
        ),
    ]
